[package]
org= "ballerinax"
name= "microsoft.teams"
version= "0.1.0"
authors = ["Ballerina"]
keywords = ["Microsoft", "Teams", "Communication"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.teams"
license = ["Apache-2.0"]

[build-options]
observability-included=true

