name: CI_pull_request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@slalpha5
        with:
          args:
            build -c ./teams
        env: 
          REFRESH_URL: ${{ secrets.REFRESH_URL }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          USER_ID_1: ${{ secrets.USER_ID_1 }}
          USER_ID_2: ${{ secrets.USER_ID_2 }}
          USER_ID_3: ${{ secrets.USER_ID_3 }}